### ISSUE TITLE
Please add copyright license to be explicit about its use

### ISSUE THREAD

**Issue by dev-msingh** [BobBDE/smart-mat-table#1]
I came across your Smart Mat-table article published on Medium. It pointed to this repository. Is this code open source or are all rights reserved for this code?
Any Github repository without a license has all rights reserved. Is this intended?

https://opensource.stackexchange.com/questions/1720/what-can-i-assume-if-a-publicly-published-project-has-no-license#:~:text=If%20a%20repository%20has%20no,permission%20from%20the%20copyright%20holder.

**Comment by dev-msingh** [comment]
Very nice article though. Thank you very much for sharing it.

**Comment by BobBDE** [comment]
Hi @mandeepx81 , 
Thank you for you comment, glad it helped you. 

This is definitly open source, I will update it !

**Comment by BobBDE** [comment]
Done :)
